### ISSUE TITLE
Sanitize /etc/hosts and hostnames on all our cloud machines

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#131]
Some jdk_jdi tests are failing due to a machine config issue, and therefore excluded.

Grabbing comment from:
https://github.com/AdoptOpenJDK/openjdk-tests/issues/132

It's a machine configuration issue.
Assign a host name to the machine by following below steps:
Choose Apple menu -> System Preferences, then click Sharing).
Click Edit, then enter a local hostname.
Add this machine name entry in /etc/hosts file with machine ip address.
Eg: 127.0.0.1 mymachine
Reboot the machine to reflect the changes.

**Comment by smlambert** [comment]
FYI @gdams 
I don't think I can make this change, as I won't have privileges to reboot the machine.

**Comment by bblondin** [comment]
This test example provided speaks about MAC OS. Is this issue limited to MAC OS? or does simular tests that run on other linux OS' also rely on the ```/etc/hosts``` file to retrieve the hostname? 

If we have testing the require the system's hostname to be listed in the ```/etc/hosts``` file (as opposed to calling the '```hostname```' command) then we will also need to ensure this change is made to all active systems and that the needed changes are applied to the playbooks.

**Comment by akolarkunnu** [comment]
It is not limited to MAC OS, in all OS it rely on configuration in the /etc/hosts file. Right now our Linux test machines are configured properly, so this issue (AdoptOpenJDK/openjdk-tests#132) is applicable/reproducible only in MAC OS.

**Comment by sxa555** [comment]
FYI I've had comparable issues with the `/etc/hosts` for the JCK as well. I haven't yet adjusted those playbooks to do the right thing (Some Ubuntus are comint to us out of the box with the system's hostname against `127.0.1.1` instead of `127.0.0.1` which causes problems)

**Comment by gdams** [comment]
perhaps we should remove `/etc/hosts` from each machine and then use ansible to template it so that they are the same across all of our providers ?

**Comment by sxa555** [comment]
Maybe, although it could be different depending on whether IPv6 and the like have been configured so that might not be ideal. And there's probably some clever reason why `127.0.1.1` was in there as well as `127.0.0.1`

**Comment by sxa555** [comment]
We definitely need some sort of consistent strategy going forward. The test machines that were causing https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/66 didn't have any entries for the system's hostname in `/etc/hosts`.

Most Ubuntu's seem to set the systems hostname against the loopback IP `127.0.0.1` but would it make more sense to have an entry with the real IP in there against the hostname? Maybe ...

Either way we could do with some consistency. Would anyone object going forward to having a strategy of making sure the hostname on the machine is a bit more consistent with what's in jenkins? For that mauve test failure the machine calls itself `test-ubuntu-16-04-1` but in jenkins it is `test-osuosl-ppc64le-ubuntu-16.04-2` - it's going to make debugging a lot easier if we have them consistent when going through log files. 

@smlambert With the way this is going perhaps we should change the title of this issue to "Sanitize /etc/hosts and hostnames on all our cloud machines?" although I appreciate that you possibly need a tactical short-term fix until we've thrashed it out.

**Comment by bblondin** [comment]
Maybe something like this? thought? 
```
  - name: Update /etc/hosts file - IP FQDN hostname
    lineinfile:
      dest: /etc/hosts
      regexp: "^(.*){{ ansible_hostname }}(.*)$"
      line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
      state: present
    tags: hosts_file

  - name: Update /etc/hosts file - 127.0.0.1
    lineinfile:
      dest: /etc/hosts
      regexp: "^(.*)127.0.0.1(.*)$"
      line: "127.0.0.1   localhost"
      state: present
    tags: hosts_file
```

**Comment by bblondin** [comment]
I've updated the ```/etc/hosts``` file on both of our macs.
@smlambert please test and let us know if this fixes https://github.com/AdoptOpenJDK/openjdk-tests/issues/132

**Comment by sxa555** [comment]
@bblondin Wouldn't that wipe an entry such as the following (which I think we get by default on some installs):

`127.0.0.1 localhost myhostname`

and not replace it with the second section because the `127.0.0.1` entry would be removed entirely in the first section? This sort of thing has made me paranoid about doing it automatically - but I do think it's worth thrashing out ;-)

**Comment by sxa555** [comment]
We will hit an issue where we have disconnects between FQDN and the hostname on the machine - we've had to replace `.` characters in the FQDN with other characters on the machines used for the JCK for example (Can't find the relevant issue just now - will amend sometime later)

**Comment by bblondin** [comment]
@sxa555 yes it would 'replace' those entires.
but I don't think ``` 127.0.0.1 localhost *myhostname* ``` is a default
I think its simply ``` 127.0.0.1 localhost ``` or ``` 127.0.0.1 localhost localhost```

Yes: ```state:present``` will add it if the regexp doesn't match

I'd like to know more about this replacing of the peroid in the FQDN

In some case (virtual machines) there may not be a FQDN however ansible ```{{ ansible_fqdn }}``` will return just the hostname in those cases give us ```MyIPAddress MyHostname MyHostname```

**Comment by bblondin** [comment]
I think the following would be the best of both worlds:

Added ```backup: yes```, this will backup file with a timestamp. This way if there is an issue the administrator can easily recover the original file.


```
  - name: Update /etc/hosts file - IP FQDN hostname
    lineinfile:
      dest: /etc/hosts
      regexp: "^(.*){{ ansible_hostname }}(.*)$"
      line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
      state: present
      backup: yes
    tags: hosts_file

  - name: Update /etc/hosts file - 127.0.0.1
    lineinfile:
      dest: /etc/hosts
      regexp: "^(.*)127.0.0.1(.*)$"
      line: "127.0.0.1   localhost"
      state: present
      backup: yes
    tags: hosts_file

```
