### ISSUE TITLE
WinPB: Stray speech-mark still appears in %PATH% after the playbook is run.

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#1485]
Ref: 
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1205#issuecomment-606037676
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1401
https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1408

It appears that on a fresh system, a speech mark still appears after the playbook is run. This can cause issues with the part of the build that applies the Visual Studio variables to the environment: 
```
06:45:10  configure: Rewriting VS_ENV_CMD to "/cygdrive/c/progra~2/mib055~1/2017/commun~1/vc/auxili~1/build/vcvars~2.bat"
06:45:10  configure: Trying to extract Visual Studio environment variables
06:45:12  \Microsoft was unexpected at this time.
06:45:12  configure: Could not succesfully extract the envionment variables needed for the VS setup.
```

**Comment by Willsparker** [comment]
I have been able to recreate the issue. In addition, the stray speech mark causes `OpenSSL` to not be built. I hypothesise it's because the speech mark in the following code block causes the command to finish prematurely: 
```
- name: Install OpenSSL-1.1.1g 64-bit (VS2013)
  win_shell: set PATH=C:\Strawberry\perl\bin;C:\openjdk\nasm-2.13.03;%PATH% && ... etc
```
SO all that does is set the path. 
The alternative is that when it gets to executing the `MSVS` shell script that is used to set the environment variables, it errors (with the same `\Microsoft was unexpected at this time` error message above).

**Comment by Willsparker** [comment]
After running through several iterations (and coming close to madness), I abandoned the idea of using `cmd` and `setX /M`
For some reason, when running through Ansible, it refused to have correct syntax and kept giving the following error message:
```
ERROR: Invalid syntax. Default option is not allowed more than '2' time(s).
```
I think this may be to do with the double quotes in the path that is messing up the syntax of `setX /M ...`. Even going back to how it was before #1408 wouldn't succeed via Ansible - it did locally, but not with Ansible. This sort of makes me question if the task to remove the speech mark ever worked in the first place.

Anyway - I've opted for a solution that uses `powershell` , which I think also looks easier to understand what it's doing: 
```
- name: Remove double quotes from Path & Add C:/cygwin64/bin to front of path
  win_shell: |
    $NewPath=$env:path.Replace('"','')
    [Environment]::SetEnvironmentVariable("Path", "C:\cygwin64\bin;" + $NewPath, [System.EnvironmentVariableTarget]::Machine)
  args:
    executable: powershell
  when: (not cygwin_installed.stat.exists)
  tags: cygwin
```
I've tested a couple times and it does work! However, it seems unlike `setX`, new `cmd` and `powershell` windows don't reflect the change to the path until after a reboot- so it's good we have a reboot task straight after. 
I find it quite curious why Ansible has no trouble with the unescaped quotes and double quotes here, but it really didn't like it when doing something such as: `win_shell: set /M PATH C:\cygwin64\bin;%PATH:="%` results in:
```
ERROR! failed at splitting arguments, either an unbalanced jinja2 block or quotes
```
