### ISSUE TITLE
AIX playbook should not put `/opt/freeware/bin` at start of /etc/environment

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1544]
This can break certain default AIX startup scripts which require the AIX `grep` command.

We need to determine the impact to the adoptopenjdk scripts of changing this.

@Haroon-Khel Possibly somethign we can do while switching to the invididual Role-based playbooks?

**Comment by aixtools** [comment]
The tactic I have seen most, over the years, is to either add PATH at the beginning of a script (as opposed to making something a system default), OR having variables defined to execute a specific command, e.g. GREP=/opt/freeware/bin/grep and then calling it using ${GREP}.

And after glancing at the playbook - I see you are 'installing', i.e., attempting to install, a dated version of openSSL (1.0.2.1601) while the version 1.0.2.2100 is already installed.

FYI: 
![image](https://user-images.githubusercontent.com/10852597/93395735-b84b6680-f876-11ea-9cba-f0434a6b7f1d.png)

**Comment by aixtools** [comment]
Hmm. Guess my message from yesterday did not take.

Short bit: openssl is also not current. playbook says 1601, but 2100 (1.0.2u) is current version.

**Comment by sxa** [comment]
@aixtools I think we need to be clear on why that PATH statement was there in the first case really (Doesn't appear to be commented in the playbook...) I suspect we should undo it on one of the machines and see what breaks :-)

**Comment by Haroon-Khel** [comment]
@sxa Do we know which AIX start up scripts fail as a result of this? And is the issue here that the PATH variable is simply at the **start** of `/etc/environment`, or that its there at all?

**Comment by aixtools** [comment]
One thing it breaks is rc.nfs. I wanted to do some AIX maintenaince
(using NFS) - and fell over this. It takes too much time to find and
document all the things that break because the syntax of 'coreutils'
and/or 'binutils' is different than the AIX versions.

So, it is not that it is in the PATH, but that it is first. Note: if a
nodejs command is requiring a coreutils/binutils command syntax - and it
is not providing the PATH - then that will break.

In short, the 'bad' is that the systems are unmanageable. Updates cannot
be applied (at least not on the system I first saw this, and it had not
changed the PATH - it had overwritten /usr/bin/grep.

Hope this helps,
Michael (aka aixtools)

**Comment by aixtools** [comment]
Smarter now: I see where it happens in aix.yml
```

      ######################################
      # Add bash to available login shells #
      ######################################
        - name: Add bash to available login shells
          replace:
            path: /etc/security/login.cfg
            regexp: 'shells = '
            replace: 'shells = /bin/bash,'
          tags: login_shell

        - name: Add bash to available login shells
          blockinfile:
            dest: /etc/shells
            block: |
              /bin/bash
          tags: login_shell

        - name: Set variables for global environment
          blockinfile:
            dest: /etc/environment
            block: |
              AIXTHREAD_HRT=true
              PKG_CONFIG_PATH=/opt/freeware/lib64/pkgconfig:/opt/freeware/lib/pkgconfig
              PERL5LIB=/opt/freemarker/lib/perl5
          tags: login_shell

        - name: Add freeware and xlc to PATH for global environment
          replace:
            path: /etc/environment
            regexp: 'PATH=/usr/bin'
            replace: 'PATH=/opt/freeware/bin:/opt/IBM/xlC/13.1.3/bin:/usr/bin'
          tags: login_shell

```
As I mention in #1581 there are some assumptions here.

* Classically, tools such as compilers - and java - are appended to the PATH, not pre-pended.
* This code does not check if the admins had already placed xlC (must it be C++, or does xlc (no C++) suffice?
* This code combines several, I would consider not related, under the heading "bash is included in login_shells". Again, it does not check if bash is already included, it just prepends it.
