### ISSUE TITLE
platforms/aix.yml makes assumptions it should not be making, e.g., that everything is in /usr/bin

### ISSUE THREAD

**Issue by aixtools** [AdoptOpenJDK/openjdk-infrastructure#1581]
Just ran the playbook on an as generic (vanilla) system as possible.

Delta from fresh install:
1) /var/ssl/cacerts.pem 
2) python3.6 installed
3) git installed (to clone the infrastructure site)
4) wget and curl installed (to fetch the above - and below)
5) ansible-2.10 installed

Running the aix.yml playbook gives:

```
(py36) root@p9-aix1-ojdk06:[/root/openjdk-infrastructure/ansible]ansible-playbook -i "localhost," -C --skip-tags adoptopenjdk,jenkins playbooks/aix.yml
/opt/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py:177: CryptographyDeprecationWarning: OpenSSL version 1.0.2 is no longer supported by the OpenSSL project, please upgrade. The next version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning,
[DEPRECATION WARNING]: DEFAULT_SQUASH_ACTIONS option, Loop squashing is deprecated and this configuration will no longer be used , use a list directly with the module argument instead. This
feature will be removed in version 2.11. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [all] **************************************************************************************************************************************************************************************

TASK [Load AdoptOpenJDKs variable file] *********************************************************************************************************************************************************
ok: [localhost]

TASK [Check if bash is installed] ***************************************************************************************************************************************************************
[WARNING]: No python interpreters found for host localhost (tried ['/usr/bin/python', 'python3.7', 'python3.6', 'python3.5', 'python2.7', 'python2.6', '/usr/libexec/platform-python',
'/usr/bin/python3', 'python'])
fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Shared connection to localhost closed.\r\n", "module_stdout": "/bin/sh: /usr/bin/python:  not found\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 127}
...ignoring

TASK [install bash] *****************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": ["Could not detect which major revision of yum is in use, which is required to determine module backend.", "You should manually specify use_backend to tell the module whether to use the yum (yum3) or dnf (yum4) backend})"]}

PLAY RECAP **************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1

```
Issues:
* as I do not know ansible (yet) - what is causing the depreciation warning re `Loop Squashing`. If this is part of aix.yml, I'll need help understanding where/what to change.
* OpenSSL - have to figure out where that is coming from - perhaps the Python build and the OpenSSL library it calls. In any case, not, imho, and aixyml issue
* No python interpreters - needs improved checking - rather than looking at file-system should (also) look at the installed software database(s). Assuming it is installed in /usr/bin is wrong. It may have been there in the past - but it will not be there in the future.
* yum: this is a separate discussion - why even bother. The OSS packages needed by nodejs are not random - they can all be downloaded individually and installed by either rpm and/or installp. afaik yum4 (dnf) is not available for AIX.
* bash check: that bash is wanted is not an issue - should not depend on yum to install it - imho.

**Comment by aixtools** [comment]
OK. I have done some massageing of the test system - such as add a symbolic link python3.6 in /usr/bin. (Where it points is not relevant atm - only that this block fails:
a) both bash and python are installed
b) I tried modifying the PATH
c) after adding symbolic link /usr/bin/python3.6 ==> /some/where/else/python3.6 -- I get the following message(s)
```

TASK [Load AdoptOpenJDKs variable file] *********************************************************************************************************************************************************
ok: [localhost]

TASK [Check if bash is installed] ***************************************************************************************************************************************************************
skipping: [localhost]

TASK [install bash] *****************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'does_bash_exist.rc != 0' failed. The error was: error while evaluating conditional (does_bash_exist.rc != 0): 'dict object' has no attribute 'rc'\n\nThe error appears to be in '/root/openjdk-infrastructure/ansible/playbooks/aix.yml': line 28, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n          ignore_errors: yes\n        - name: install bash\n          ^ here\n"}

PLAY RECAP **************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

```

**Comment by aixtools** [comment]
OK. So, no comments yet.

My humble opinion:

The aix.yml should be a sort of process management flow.

Step 1: verify that licensed requirements are installed - including - especially! things such as XLC and other items that come from IBM AIX BOS (aka, the DVD's).

Step 2: if/when needed - verify that known issues have been addressed.

IMHO: key in these first two steps is that no changes are made - other than perhaps copying a script for execution as is currently done for the "filesystems" config script. ** speaking of ** the part of the file systems script that checks on the hdisk minimum size would be moved to step 2 (above). The disk, better volume group size is, or it is not sufficient.

The purpose: these are all elements that are, or should be, the responsibility, of an "AIX admin" aka system owner. Perhaps 'node.js and/or AdoptOpenJDK' have been 'owners', but to be truely supporting as an OSS project open to others you should protect yourself and not be installing things requiring a license AND - initially verifying a system is "ready to go" for the project (nodejs/AdoptOpenJDK).

In following steps - the strategy I am considering now is to write scripts that get executed as a 'task' - again, taking the filesystems approach as a template:
```

      ################################
      # AIX filesystem configuration #
      ################################

        - name: Download AIX filesystem configuration script
          get_url:
            url: https://raw.githubusercontent.com/AdoptOpenJDK/openjdk-infrastructure/master/ansible/playbooks/scripts/AIX_filesystem_config.sh
            dest: /tmp/AIX_filesystem_config.sh
            mode: 0775
            validate_certs: no
          tags: filesystem

        - name: Execute AIX filesystem configuration script
          command: /tmp/AIX_filesystem_config.sh
          tags: filesystem

        - name: Remove AIX filesystem configuration script
          file:
            state: absent
            path: /tmp/AIX_filesystem_config.sh
          tags: filesystem
```

* I suspect, as I go through more of aix.yml, that this is already the approach.

_FYI: The need for a ramdisk has been resolved (by me). The issue is when lots (10's and 100's of thousands of temporary files are created) the lag introduced by the journal logging creates a lag that cannot be parallelized. Taking OSU as an example - as it uses vscsi only - the top speed for jfs(2) logging seems to be between 8 and 10Mbs.

The 'ramdisk' is not faster than a regular filesystem - once jfs(2) logging is switched off. So the actual solution is to ensure that the project work directory is not being "JFS2" logged, e.g., /home is mounted with attribute log=NULL)._


Comments welcome!! actually, needed!!

**Comment by aixtools** [comment]
Question: are these being installed to support 'yum', or are they actually needed by node.js/AdoptOpenJDK.

If the answer is yes - yum needs these (as it does have some - imho - extraordinary pre-requisites (and yum.sh also has pre-requisites) -- I have a second question:

which of these OSS packages are actually needed - explicitly - by node.js/AdoptOpenJDK?

```
        - name: Install yum package support
          yum: name={{ item }} state=present update_cache=yes
          with_items:
            - autoconf
            - bc
            - bison
            - coreutils
            - cpio
            - cups-devel
            - cups-libs
            - expect
            - flex
            - freetype2-devel
            - fontconfig-devel
            - gawk
            - git
            - grep
            - libXrender-devel
            - libffi-devel
            - make
            - m4
            - pcre
            - pkg-config
            - popt
            - sed
            - sudo
            - tar
            - tcl
            - tk
            - unzip
            - wget
            - xz-libs
            - zip
            - zsh
          tags: yum

```
