### ISSUE TITLE
Ansible request for CentOS6 adoptopenjdk_install role

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#1877]
Affecting both `VPC` and the CentOS6 GitHub Check: 
- https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/997/OS=CentOS6,label=vagrant/console
- https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1875/checks?check_run_id=1804893220

- [ ] Missing install
- [x] Bug in ansible playbook
- [ ] Request for new playbook addition

Details:

The issue is with `adoptopenjdk_install` : 
```
fatal: [localhost]: FAILED! => {"attempts": 3, "changed": false, "msg": "Failed to validate the SSL certificate for github-releases.githubusercontent.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine  (the python executable used (/usr/bin/python) is version: 2.6.6 (r266:84292, Jun 20 2019, 14:14:55) [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]) or you can install the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: hostname 'github-releases.githubusercontent.com' doesn't match either of '*.githubassets.com', 'githubassets.com'.", "status": -1, "url": "https://api.adoptopenjdk.net/v3/binary/latest/8/ga/linux/x64/jdk/hotspot/normal/adoptopenjdk?project=jdk"}
```
Apparently it's failing to validate the SSL Certificate for github-releases.githubusercontent.com. If all else fails, we can use `validate_certs=False`, but this is a last resort.

**Comment by Willsparker** [comment]
Replicated problem on local CentOS6 VM. Looking at doing as the Issue suggests, and updating Python to 2.7.9, however, we'll still have to ensure the GH check and the VPC machine has Python 2.7.9

**Comment by Willsparker** [comment]
Hmm, installing `2.7.9` ruined my Ansible install.... Not something I want to do on the VPC machine

**Comment by Willsparker** [comment]
Oh - my mistake - the error message is talking about the CentOS6 Python install, I think.
Installing it on CentOS6, following this https://www.linuxtweaks.in/how-to-install-python-2-7-in-centosrhel/ (and changing `2.7.8` for `2.7.9`). I then symlinked `/usr/bin/python` to `/usr/local/bin/python2.7`. This also retains the original python 2.6 at `/usr/bin/python2`. This makes the role work! 
@sxa Because a lot depends on Python, is it okay to have the playbook install `2.7` ? Alternatively, to fix VPC, we can have python2.7 installed in the provisioning script. As for GH check, I can't see where anything might be installed before the playbook is run on the docker image?

**Comment by Willsparker** [comment]
I've made a Python 2.7.9 install role, which can be seen at https://github.com/Willsparker/openjdk-infrastructure/tree/1877 . Currently testing with `VPC` : https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1002/

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1005/
Seems this will have implications later on. I'll try to fix that issue and then if anymore come up , I think I'll abandon the idea of installing Python 2.7.9 and try to find a solution to the original problem.

**Comment by Willsparker** [comment]
Okay, yep, scrap the Python 2.7.9 idea. I'll put the yaml here, just in case we ever want to come back to it:
```
---
####################
# Python Bootstrap #
####################

# Check if Python is installed, and it's version. If Python isn't installed, or it's at a version below 2.7.9, install Python 2.7.9.
# Currently only for CentOS6. See: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1877

- name: Check for Python 2's version
  shell: python -V 2>&1 | grep -Po '(?<=Python )(.+)'
  register: python_version
  ignore_errors: yes
  when:
    - (ansible_distribution == "CentOS") and (ansible_distribution_major_version == "6")
  tags: 
    - python_bootstrap

- name: Yum install prerequisites to build Python 2.7.9
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - xz-libs
    - wget
  when: 
    - (ansible_distribution == "CentOS") and (ansible_distribution_major_version == "6")
    - (python_version.rc != 0) or (python_version.rc == 0 and python_version.stdout is version_compare('2.7.9', operator='lt') )
  tags:
    - python_bootstrap

- name: Download & extract Python 2.7.9 source
  unarchive: 
    src: http://www.python.org/ftp/python/2.7.9/Python-2.7.9.tar.xz 
    dest: /tmp/
    remote_src: yes
    mode: 0755
  retries: 3 
  delay: 5
  register: python_download
  until: python_download is not failed
  when: 
    - (ansible_distribution == "CentOS") and (ansible_distribution_major_version == "6")
    - (python_version.rc != 0) or (python_version.rc == 0 and python_version.stdout is version_compare('2.7.9', operator='lt') )
  tags:
    - python_bootstrap

- name: Configure, build & make/make altinstall
  shell: |
    cd /tmp/Python-2.7.9 && ./configure --prefix=/usr/local && make && make altinstall
  when:
    - (ansible_distribution == "CentOS") and (ansible_distribution_major_version == "6")
    - (python_version.rc != 0) or (python_version.rc == 0 and python_version.stdout is version_compare('2.7.9', operator='lt') )
  tags:
    - python_bootstrap

- name: Symlink Python 2.7.9 to /usr/bin/python
  file:
    src: /usr/local/bin/python2.7
    dest: /usr/bin/python
    state: link
    force: yes
  when:
    - (ansible_distribution == "CentOS") and (ansible_distribution_major_version == "6")
    - (python_version.rc != 0) or (python_version.rc == 0 and python_version.stdout is version_compare('2.7.9', operator='lt') )
  tags:
    - python_bootstrap
```
Onwards
