### ISSUE TITLE
VPC: Debian10 apt-get upgrade GRUB issue

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#1980]
Log: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Debian10,label=vagrant/1086/console

I hit this whilst running locally too - the issue appears to be that `grub-pc` is being upgraded, which causes a pop-up, that Ansible can't handle. I googled around , and found this: https://unix.stackexchange.com/questions/422282/apt-get-y-upgrade-keep-asking-me-to-confirm-keep-tmp-grub-xc3mmkp0zx-file-and , and supposedly setting `DEBIAN_FRONTEND=noninteractive` is meant to fix it, however I was unable to get this to work- having modified the ansible task:

```
- name: Run apt-get upgrade
  apt:
    upgrade: safe
    update_cache: yes
    force: yes
    dpkg_options: 'force-confdef'
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags: patch_update
```
This gave a different error message (cut out the not needed bits):
```
"Setting up grub-pc (2.02+dfsg1-20+deb10u3) ...", "/dev/vda does not exist, so cannot grub-install to it!", "You must correct your GRUB install devices before proceeding:", "", "  dpkg-reconfigure grub-pc", "dpkg: error processing package grub-pc (--configure):", " installed grub-pc package post-installation script subprocess returned error exit status 1", "Errors were encountered while processing:", " grub-pc"]}
```
