### ISSUE TITLE
Ensure user has the right version of Ansible

### ISSUE THREAD

**Issue by bblondin** [AdoptOpenJDK/openjdk-infrastructure#341]
A user reach out to me with an issue using our playbooks. 
The issue was that he was using an older version of Ansible that doesn't support some of the functions used throughout the playbooks.

We should add an `assert` check at the start of the playbook so that it will error out with a useful message to the enduser 

Something like this should work:

```
- name: Ensure minimum Ansible version
      assert:
        that:
          - "{{ ansible_version.string | version_compare('2.4', '>=') }}"
        msg: Ansible 2.4 or above is required
```
